# Site settings
title: Bart Van Itterbeeck
email: bart@bartvi.be
description: > # this means to ignore newlines until "baseurl:"
  Bart Van Itterbeeck. Full stack web developer and all-round awesome person.
  Hire me now !
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bartvi.be" # the base hostname & protocol for your site
twitter_username: BartBarto
github_username:  BartBarto
facebook_username:  bartvanitterbeeck
pinterest_username:  bartbarto
google_plus_id:  +BartVanItterbeeck
linkedin_id:  87762872

# Build settings
markdown: kramdown
